# Generated by Django 5.0.4 on 2024-04-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/home/mezo-developer/Documents/Projects_Django/Blog/main_blog/main_blog/media/images/2024/01/06/fut.jpeg', upload_to='images/%Y/%M/%d'),
        ),
    ]
